name: Build-Siv3D-App
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Release
        run: msbuild YourProject.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pythagoras-Game
          path: App/  # Siv3Dの標準出力先
