name: Build-Pythagoras-Siv3D
on:
  push:
    branches-ignore: [ main ] # main以外で動かす

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Game
        shell: pwsh
        run: |
          $sln = Get-ChildItem -Filter *.sln -Recurse | Select-Object -First 1
          nuget restore $sln.FullName
          msbuild $sln.FullName /p:Configuration=Release /p:Platform=x64

      - name: Upload Artifact
        id: artifact-upload # IDを振っておく
        uses: actions/upload-artifact@v4
        with:
          name: Pythagoras-Game-EXE
          path: |
            App/
            x64/Release/*.exe

      - name: Show Download URL
        shell: pwsh
        run: |
          # 成果物のダウンロードページURLを表示
          $url = "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          Write-Host "--------------------------------------------------"
          Write-Host "ビルド完了！成果物は以下のURLからダウンロードしてください："
          Write-Host $url
          Write-Host "--------------------------------------------------"
